name: Deploy Backend to Azure Web App

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend_azure-deploy.yml"
    branches:
      - main

defaults:
  run:
    working-directory: backend

env:
  DOTNET_ROOT: "/opt/dotnet"
  dotnet-version: 5.0.x
  appName: backend-${{ secrets.AzureAppService_AppName }}

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.node-version }}

      - name: Build with dotnet
        run: |
          dotnet restore
          dotnet build --no-restore AuthService || true
          dotnet build --no-restore GoogleService || true
          dotnet build --no-restore
          dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/${{ env.appName }}

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.appName }}
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Backend }}
          package: ${{ env.DOTNET_ROOT }}/${{ env.appName }}
